/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct rand_data {
    pub _bindgen_opaque_blob: [u64; 26usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rand_data"][::std::mem::size_of::<rand_data>() - 208usize];
    ["Alignment of rand_data"][::std::mem::align_of::<rand_data>() - 8usize];
};
unsafe extern "C" {
    pub fn jent_read_entropy(
        ec: *mut rand_data,
        data: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> isize;
}
unsafe extern "C" {
    pub fn jent_entropy_collector_alloc(
        osr: ::std::os::raw::c_uint,
        flags: ::std::os::raw::c_uint,
    ) -> *mut rand_data;
}
unsafe extern "C" {
    pub fn jent_entropy_collector_free(entropy_collector: *mut rand_data);
}
unsafe extern "C" {
    pub fn jent_entropy_init() -> ::std::os::raw::c_int;
}
